---
title: "Find a Gene custom project"
author: "Hailey Heirigs (PID: A16962278)"
format: html
---

## Find a Gene Homework

```{r}
library(bio3d)

pth <- "PersonalFindaGene_e9930/"
pdb.files <- list.files(path = pth, full.names = TRUE, pattern = ".pdb")
```

Align and superimpose all these models 
```{r}
file.exists(pdb.files)
```

```{r}
pdbs <- pdbaln(pdb.files, fit = TRUE, exefile="msa")
```

```{r}
library(bio3dview)

view.pdbs(pdbs)
```

```{r}
plot(pdbs$b[1,], typ="l", ylim=c(0,100), ylab="pLDDT score")
lines(pdbs$b[2,], typ = "l", col = "blue")
lines(pdbs$b[3,], typ = "l", col = "green")
lines(pdbs$b[4,], typ = "l", col = "orange")
lines(pdbs$b[5,], typ = "l", col = "red")
```

```{r}
# File names for all PDB models
pdb_files <- list.files(path=pth,
                        pattern="*.pdb",
                        full.names = TRUE)

# Print our PDB file names
basename(pdb_files)
```
```{r}
library(bio3d)

# Read all data from Models 
#  and superpose/fit coords
pdbs <- pdbaln(pdb_files, fit=TRUE, exefile="msa")
```
```{r}
rd <- rmsd(pdbs, fit=T)
range(rd)

library(pheatmap)

colnames(rd) <- paste0("m",1:5)
rownames(rd) <- paste0("m",1:5)
pheatmap(rd)
```

```{r}
# Read a reference PDB structure
pdb <- read.pdb("1hsg")
```




